.org 16
.section "battle0 static strings 0" overwrite
  .db 1
  .dw battle0_string0
.ends
.unbackground 19 22
.org 23
.section "battle0 static strings 1" overwrite
  .db 1
  .dw battle0_string1
.ends
.unbackground 26 27
.org 28
.section "battle0 static strings 2" overwrite
  .db 1
  .dw battle0_string2
.ends
.unbackground 31 32
.org 33
.section "battle0 static strings 3" overwrite
  .db 1
  .dw battle0_string3
.ends
.unbackground 36 47
.org 48
.section "battle0 static strings 4" overwrite
  .db 1
  .dw battle0_string4
.ends
.unbackground 51 52
.org 53
.section "battle0 static strings 5" overwrite
  .db 1
  .dw battle0_string5
.ends
.unbackground 56 73
.org 74
.section "battle0 static strings 6" overwrite
  .db 1
  .dw battle0_string6
.ends
.unbackground 77 78
.org 79
.section "battle0 static strings 7" overwrite
  .db 1
  .dw battle0_string7
.ends
.unbackground 82 85
.org 86
.section "battle0 static strings 8" overwrite
  .db 1
  .dw battle0_string8
.ends
.unbackground 89 94
.org 95
.section "battle0 static strings 9" overwrite
  .db 1
  .dw battle0_string9
.ends
.unbackground 98 107
.org 108
.section "battle0 static strings 10" overwrite
  .db 1
  .dw battle0_string10
.ends
.unbackground 111 118
.org 119
.section "battle0 static strings 11" overwrite
  .db 1
  .dw battle0_string11
.ends
.unbackground 122 131
.org 132
.section "battle0 static strings 12" overwrite
  .db 1
  .dw battle0_string12
.ends
.unbackground 135 140
.org 141
.section "battle0 static strings 13" overwrite
  .db 1
  .dw battle0_string13
.ends
.unbackground 144 149
.org 150
.section "battle0 static strings 14" overwrite
  .db 1
  .dw battle0_string14
.ends
.unbackground 153 166
.org 167
.section "battle0 static strings 15" overwrite
  .db 1
  .dw battle0_string15
.ends
.unbackground 170 171
.org 172
.section "battle0 static strings 16" overwrite
  .db 1
  .dw battle0_string16
.ends
.unbackground 175 188
.org 189
.section "battle0 static strings 17" overwrite
  .db 1
  .dw battle0_string17
.ends
.unbackground 192 217
.org 218
.section "battle0 static strings 18" overwrite
  .db 1
  .dw battle0_string18
.ends
.unbackground 221 244
.org 245
.section "battle0 static strings 19" overwrite
  .db 1
  .dw battle0_string19
.ends
.unbackground 248 265
.org 266
.section "battle0 static strings 20" overwrite
  .db 1
  .dw battle0_string20
.ends
.unbackground 269 272
.org 273
.section "battle0 static strings 21" overwrite
  .db 1
  .dw battle0_string21
.ends
.org 276
.section "battle0 static strings 22" overwrite
  .db 1
  .dw battle0_string22
.ends
.unbackground 279 296
.org 297
.section "battle0 static strings 23" overwrite
  .db 1
  .dw battle0_string23
.ends
.org 300
.section "battle0 static strings 24" overwrite
  .db 1
  .dw battle0_string24
.ends
.unbackground 303 312
.org 313
.section "battle0 static strings 25" overwrite
  .db 1
  .dw battle0_string25
.ends
.unbackground 316 319
.org 320
.section "battle0 static strings 26" overwrite
  .db 1
  .dw battle0_string26
.ends
.unbackground 323 326
.org 328
.section "battle0 static strings 28" overwrite
  .db 1
  .dw battle0_string28
.ends
.unbackground 331 342
.org 343
.section "battle0 static strings 29" overwrite
  .db 1
  .dw battle0_string29
.ends
.unbackground 346 355
.org 356
.section "battle0 static strings 30" overwrite
  .db 1
  .dw battle0_string30
.ends
.unbackground 359 382
.org 383
.section "battle0 static strings 31" overwrite
  .db 1
  .dw battle0_string31
.ends
.unbackground 386 419
