.org 15
.section "battle2 static strings 0" overwrite
  .db 1
  .dw battle2_string0
.ends
.org 18
.section "battle2 static strings 1" overwrite
  .db 1
  .dw battle2_string1
.ends
.org 21
.section "battle2 static strings 2" overwrite
  .db 1
  .dw battle2_string2
.ends
.unbackground 24 27
.org 28
.section "battle2 static strings 3" overwrite
  .db 1
  .dw battle2_string3
.ends
.unbackground 31 32
.org 33
.section "battle2 static strings 4" overwrite
  .db 1
  .dw battle2_string4
.ends
.unbackground 36 37
.org 38
.section "battle2 static strings 5" overwrite
  .db 1
  .dw battle2_string5
.ends
.unbackground 41 52
.org 53
.section "battle2 static strings 6" overwrite
  .db 1
  .dw battle2_string6
.ends
.unbackground 56 57
.org 58
.section "battle2 static strings 7" overwrite
  .db 1
  .dw battle2_string7
.ends
.unbackground 61 66
.org 67
.section "battle2 static strings 8" overwrite
  .db 1
  .dw battle2_string8
.ends
.unbackground 70 79
.org 80
.section "battle2 static strings 9" overwrite
  .db 1
  .dw battle2_string9
.ends
.unbackground 83 90
.org 91
.section "battle2 static strings 10" overwrite
  .db 1
  .dw battle2_string10
.ends
.unbackground 94 103
.org 104
.section "battle2 static strings 11" overwrite
  .db 1
  .dw battle2_string11
.ends
.unbackground 107 112
.org 113
.section "battle2 static strings 12" overwrite
  .db 1
  .dw battle2_string12
.ends
.unbackground 116 121
.org 122
.section "battle2 static strings 13" overwrite
  .db 1
  .dw battle2_string13
.ends
.unbackground 125 138
.org 139
.section "battle2 static strings 14" overwrite
  .db 1
  .dw battle2_string14
.ends
.unbackground 142 145
.org 146
.section "battle2 static strings 15" overwrite
  .db 1
  .dw battle2_string15
.ends
.unbackground 149 160
.org 161
.section "battle2 static strings 16" overwrite
  .db 1
  .dw battle2_string16
.ends
.unbackground 164 177
.org 178
.section "battle2 static strings 17" overwrite
  .db 1
  .dw battle2_string17
.ends
.unbackground 181 206
.org 207
.section "battle2 static strings 18" overwrite
  .db 1
  .dw battle2_string18
.ends
.unbackground 210 229
.org 230
.section "battle2 static strings 19" overwrite
  .db 1
  .dw battle2_string19
.ends
.unbackground 233 236
.org 237
.section "battle2 static strings 20" overwrite
  .db 1
  .dw battle2_string20
.ends
.org 240
.section "battle2 static strings 21" overwrite
  .db 1
  .dw battle2_string21
.ends
.unbackground 243 260
.org 261
.section "battle2 static strings 22" overwrite
  .db 1
  .dw battle2_string22
.ends
.org 264
.section "battle2 static strings 23" overwrite
  .db 1
  .dw battle2_string23
.ends
.unbackground 267 276
.org 277
.section "battle2 static strings 24" overwrite
  .db 1
  .dw battle2_string24
.ends
.unbackground 280 283
.org 284
.section "battle2 static strings 25" overwrite
  .db 1
  .dw battle2_string25
.ends
.unbackground 287 290
