.org 15
.section "battle3 static strings 0" overwrite
  .db 1
  .dw battle3_string0
.ends
.org 18
.section "battle3 static strings 1" overwrite
  .db 1
  .dw battle3_string1
.ends
.org 21
.section "battle3 static strings 2" overwrite
  .db 1
  .dw battle3_string2
.ends
.unbackground 24 27
.org 28
.section "battle3 static strings 3" overwrite
  .db 1
  .dw battle3_string3
.ends
.unbackground 31 32
.org 33
.section "battle3 static strings 4" overwrite
  .db 1
  .dw battle3_string4
.ends
.unbackground 36 37
.org 38
.section "battle3 static strings 5" overwrite
  .db 1
  .dw battle3_string5
.ends
.unbackground 41 52
.org 53
.section "battle3 static strings 6" overwrite
  .db 1
  .dw battle3_string6
.ends
.unbackground 56 57
.org 58
.section "battle3 static strings 7" overwrite
  .db 1
  .dw battle3_string7
.ends
.unbackground 61 66
.org 67
.section "battle3 static strings 8" overwrite
  .db 1
  .dw battle3_string8
.ends
.unbackground 70 79
.org 80
.section "battle3 static strings 9" overwrite
  .db 1
  .dw battle3_string9
.ends
.unbackground 83 90
.org 91
.section "battle3 static strings 10" overwrite
  .db 1
  .dw battle3_string10
.ends
.unbackground 94 103
.org 104
.section "battle3 static strings 11" overwrite
  .db 1
  .dw battle3_string11
.ends
.unbackground 107 112
.org 113
.section "battle3 static strings 12" overwrite
  .db 1
  .dw battle3_string12
.ends
.unbackground 116 121
.org 122
.section "battle3 static strings 13" overwrite
  .db 1
  .dw battle3_string13
.ends
.unbackground 125 138
.org 139
.section "battle3 static strings 14" overwrite
  .db 1
  .dw battle3_string14
.ends
.unbackground 142 147
.org 148
.section "battle3 static strings 15" overwrite
  .db 1
  .dw battle3_string15
.ends
.unbackground 151 162
.org 163
.section "battle3 static strings 16" overwrite
  .db 1
  .dw battle3_string16
.ends
.unbackground 166 179
.org 180
.section "battle3 static strings 17" overwrite
  .db 1
  .dw battle3_string17
.ends
.unbackground 183 208
.org 209
.section "battle3 static strings 18" overwrite
  .db 1
  .dw battle3_string18
.ends
.unbackground 212 233
.org 234
.section "battle3 static strings 19" overwrite
  .db 1
  .dw battle3_string19
.ends
.unbackground 237 262
.org 263
.section "battle3 static strings 20" overwrite
  .db 1
  .dw battle3_string20
.ends
.unbackground 266 269
.org 270
.section "battle3 static strings 21" overwrite
  .db 1
  .dw battle3_string21
.ends
.org 273
.section "battle3 static strings 22" overwrite
  .db 1
  .dw battle3_string22
.ends
.unbackground 276 293
.org 294
.section "battle3 static strings 23" overwrite
  .db 1
  .dw battle3_string23
.ends
.org 297
.section "battle3 static strings 24" overwrite
  .db 1
  .dw battle3_string24
.ends
.unbackground 300 309
.org 310
.section "battle3 static strings 25" overwrite
  .db 1
  .dw battle3_string25
.ends
.unbackground 313 316
.org 317
.section "battle3 static strings 26" overwrite
  .db 1
  .dw battle3_string26
.ends
.unbackground 320 323
