.org 4916
.section "battle3_ally static strings 0" overwrite
  .db 1
  .dw battle3_ally_string0
.ends
.unbackground 4919 4944
.org 4945
.section "battle3_ally static strings 1" overwrite
  .db 1
  .dw battle3_ally_string1
.ends
.unbackground 4948 4953
.org 4962
.section "battle3_ally static strings 10" overwrite
  .db 1
  .dw battle3_ally_string10
.ends
.unbackground 4965 4974
.org 4976
.section "battle3_ally static strings 12" overwrite
  .db 1
  .dw battle3_ally_string12
.ends
.unbackground 4979 4980
