.org 4696
.section "battle2_ally static strings 0" overwrite
  .db 1
  .dw battle2_ally_string0
.ends
.unbackground 4699 4722
.org 4723
.section "battle2_ally static strings 1" overwrite
  .db 1
  .dw battle2_ally_string1
.ends
.unbackground 4726 4731
.org 4740
.section "battle2_ally static strings 10" overwrite
  .db 1
  .dw battle2_ally_string10
.ends
.unbackground 4743 4752
.org 4754
.section "battle2_ally static strings 12" overwrite
  .db 1
  .dw battle2_ally_string12
.ends
.unbackground 4757 4758
