.org 17
.section "battle4 static strings 0" overwrite
  .db 1
  .dw battle4_string0
.ends
.org 20
.section "battle4 static strings 1" overwrite
  .db 1
  .dw battle4_string1
.ends
.org 23
.section "battle4 static strings 2" overwrite
  .db 1
  .dw battle4_string2
.ends
.unbackground 26 29
.org 30
.section "battle4 static strings 3" overwrite
  .db 1
  .dw battle4_string3
.ends
.unbackground 33 34
.org 35
.section "battle4 static strings 4" overwrite
  .db 1
  .dw battle4_string4
.ends
.unbackground 38 39
.org 40
.section "battle4 static strings 5" overwrite
  .db 1
  .dw battle4_string5
.ends
.unbackground 43 46
.org 47
.section "battle4 static strings 6" overwrite
  .db 1
  .dw battle4_string6
.ends
.unbackground 50 51
.org 52
.section "battle4 static strings 7" overwrite
  .db 1
  .dw battle4_string7
.ends
.unbackground 55 60
.org 61
.section "battle4 static strings 8" overwrite
  .db 1
  .dw battle4_string8
.ends
.unbackground 64 73
.org 74
.section "battle4 static strings 9" overwrite
  .db 1
  .dw battle4_string9
.ends
.unbackground 77 84
.org 85
.section "battle4 static strings 10" overwrite
  .db 1
  .dw battle4_string10
.ends
.unbackground 88 95
.org 96
.section "battle4 static strings 11" overwrite
  .db 1
  .dw battle4_string11
.ends
.unbackground 99 106
.org 107
.section "battle4 static strings 12" overwrite
  .db 1
  .dw battle4_string12
.ends
.unbackground 110 127
.org 128
.section "battle4 static strings 13" overwrite
  .db 1
  .dw battle4_string13
.ends
.unbackground 131 150
.org 151
.section "battle4 static strings 14" overwrite
  .db 1
  .dw battle4_string14
.ends
.unbackground 154 179
.org 180
.section "battle4 static strings 15" overwrite
  .db 1
  .dw battle4_string15
.ends
.unbackground 183 206
.org 207
.section "battle4 static strings 16" overwrite
  .db 1
  .dw battle4_string16
.ends
.unbackground 210 213
.org 214
.section "battle4 static strings 17" overwrite
  .db 1
  .dw battle4_string17
.ends
.org 217
.section "battle4 static strings 18" overwrite
  .db 1
  .dw battle4_string18
.ends
.unbackground 220 237
.org 238
.section "battle4 static strings 19" overwrite
  .db 1
  .dw battle4_string19
.ends
.org 241
.section "battle4 static strings 20" overwrite
  .db 1
  .dw battle4_string20
.ends
.unbackground 244 253
.org 254
.section "battle4 static strings 21" overwrite
  .db 1
  .dw battle4_string21
.ends
.unbackground 257 260
.org 261
.section "battle4 static strings 22" overwrite
  .db 1
  .dw battle4_string22
.ends
.unbackground 264 267
