.org 7
.section "scene19 static strings 0" overwrite
  .db 1
  .dw scene19_string0
.ends
.unbackground 10 29
.org 30
.section "scene19 static strings 1" overwrite
  .db 1
  .dw scene19_string1
.ends
.unbackground 33 46
.org 47
.section "scene19 static strings 2" overwrite
  .db 1
  .dw scene19_string2
.ends
.unbackground 50 57
.org 58
.section "scene19 static strings 3" overwrite
  .db 1
  .dw scene19_string3
.ends
.unbackground 61 86
.org 87
.section "scene19 static strings 4" overwrite
  .db 1
  .dw scene19_string4
.ends
.unbackground 90 107
.org 108
.section "scene19 static strings 5" overwrite
  .db 1
  .dw scene19_string5
.ends
.unbackground 111 124
.org 125
.section "scene19 static strings 6" overwrite
  .db 1
  .dw scene19_string6
.ends
.unbackground 128 163
.org 164
.section "scene19 static strings 7" overwrite
  .db 1
  .dw scene19_string7
.ends
.unbackground 167 192
.org 193
.section "scene19 static strings 8" overwrite
  .db 1
  .dw scene19_string8
.ends
.unbackground 196 215
.org 216
.section "scene19 static strings 9" overwrite
  .db 1
  .dw scene19_string9
.ends
.unbackground 219 240
.org 241
.section "scene19 static strings 10" overwrite
  .db 1
  .dw scene19_string10
.ends
.unbackground 244 259
.org 260
.section "scene19 static strings 11" overwrite
  .db 1
  .dw scene19_string11
.ends
.unbackground 263 288
.org 289
.section "scene19 static strings 12" overwrite
  .db 1
  .dw scene19_string12
.ends
.unbackground 292 307
