.org 3485
.section "scene1C static strings 0" overwrite
  .db 1
  .dw scene1C_string0
.ends
.unbackground 3488 3497
.org 3499
.section "scene1C static strings 2" overwrite
  .db 1
  .dw scene1C_string2
.ends
.unbackground 3502 3523
.org 3527
.section "scene1C static strings 6" overwrite
  .db 1
  .dw scene1C_string6
.ends
.unbackground 3530 3537
.org 3539
.section "scene1C static strings 8" overwrite
  .db 1
  .dw scene1C_string8
.ends
.unbackground 3542 3573
.org 3578
.section "scene1C static strings 13" overwrite
  .db 1
  .dw scene1C_string13
.ends
.unbackground 3581 3612
.org 3616
.section "scene1C static strings 17" overwrite
  .db 1
  .dw scene1C_string17
.ends
.unbackground 3619 3650
.org 3652
.section "scene1C static strings 19" overwrite
  .db 1
  .dw scene1C_string19
.ends
.unbackground 3655 3686
.org 3688
.section "scene1C static strings 21" overwrite
  .db 1
  .dw scene1C_string21
.ends
.unbackground 3691 3722
.org 3725
.section "scene1C static strings 24" overwrite
  .db 1
  .dw scene1C_string24
.ends
.unbackground 3728 3759
.org 3760
.section "scene1C static strings 25" overwrite
  .db 1
  .dw scene1C_string25
.ends
.unbackground 3763 3796
.org 3797
.section "scene1C static strings 26" overwrite
  .db 1
  .dw scene1C_string26
.ends
.unbackground 3800 3835
.org 3836
.section "scene1C static strings 27" overwrite
  .db 1
  .dw scene1C_string27
.ends
.unbackground 3839 3872
.org 3874
.section "scene1C static strings 29" overwrite
  .db 1
  .dw scene1C_string29
.ends
.unbackground 3877 3908
.org 3909
.section "scene1C static strings 30" overwrite
  .db 1
  .dw scene1C_string30
.ends
.unbackground 3912 3945
.org 3947
.section "scene1C static strings 32" overwrite
  .db 1
  .dw scene1C_string32
.ends
.unbackground 3950 3981
.org 3982
.section "scene1C static strings 33" overwrite
  .db 1
  .dw scene1C_string33
.ends
.unbackground 3985 4018
.org 4022
.section "scene1C static strings 37" overwrite
  .db 1
  .dw scene1C_string37
.ends
.unbackground 4025 4058
.org 4064
.section "scene1C static strings 43" overwrite
  .db 1
  .dw scene1C_string43
.ends
.unbackground 4067 4098
.org 4102
.section "scene1C static strings 47" overwrite
  .db 1
  .dw scene1C_string47
.ends
.unbackground 4105 4136
.org 4138
.section "scene1C static strings 49" overwrite
  .db 1
  .dw scene1C_string49
.ends
.unbackground 4141 4160
.org 4162
.section "scene1C static strings 51" overwrite
  .db 1
  .dw scene1C_string51
.ends
.unbackground 4165 4186
.org 4188
.section "scene1C static strings 53" overwrite
  .db 1
  .dw scene1C_string53
.ends
.unbackground 4191 4198
.org 4199
.section "scene1C static strings 54" overwrite
  .db 1
  .dw scene1C_string54
.ends
.unbackground 4202 4223
.org 4225
.section "scene1C static strings 56" overwrite
  .db 1
  .dw scene1C_string56
.ends
.unbackground 4228 4253
.org 4255
.section "scene1C static strings 58" overwrite
  .db 1
  .dw scene1C_string58
.ends
.unbackground 4258 4279
.org 4281
.section "scene1C static strings 60" overwrite
  .db 1
  .dw scene1C_string60
.ends
.unbackground 4284 4305
.org 4307
.section "scene1C static strings 62" overwrite
  .db 1
  .dw scene1C_string62
.ends
.unbackground 4310 4331
.org 4334
.section "scene1C static strings 65" overwrite
  .db 1
  .dw scene1C_string65
.ends
.unbackground 4337 4362
.org 4364
.section "scene1C static strings 67" overwrite
  .db 1
  .dw scene1C_string67
.ends
.unbackground 4367 4384
.org 4385
.section "scene1C static strings 68" overwrite
  .db 1
  .dw scene1C_string68
.ends
.unbackground 4388 4409
.org 4410
.section "scene1C static strings 69" overwrite
  .db 1
  .dw scene1C_string69
.ends
.unbackground 4413 4436
.org 4437
.section "scene1C static strings 70" overwrite
  .db 1
  .dw scene1C_string70
.ends
.unbackground 4440 4461
.org 4463
.section "scene1C static strings 72" overwrite
  .db 1
  .dw scene1C_string72
.ends
.unbackground 4466 4473
.org 4475
.section "scene1C static strings 74" overwrite
  .db 1
  .dw scene1C_string74
.ends
.unbackground 4478 4501
.org 4505
.section "scene1C static strings 78" overwrite
  .db 1
  .dw scene1C_string78
.ends
.unbackground 4508 4533
.org 4535
.section "scene1C static strings 80" overwrite
  .db 1
  .dw scene1C_string80
.ends
.unbackground 4538 4567
.org 4570
.section "scene1C static strings 83" overwrite
  .db 1
  .dw scene1C_string83
.ends
.unbackground 4573 4612
.org 4613
.section "scene1C static strings 84" overwrite
  .db 1
  .dw scene1C_string84
.ends
.unbackground 4616 4641
.org 4642
.section "scene1C static strings 85" overwrite
  .db 1
  .dw scene1C_string85
.ends
.unbackground 4645 4678
.org 4679
.section "scene1C static strings 86" overwrite
  .db 1
  .dw scene1C_string86
.ends
.unbackground 4682 4699
.org 4700
.section "scene1C static strings 87" overwrite
  .db 1
  .dw scene1C_string87
.ends
.unbackground 4703 4720
.org 4721
.section "scene1C static strings 88" overwrite
  .db 1
  .dw scene1C_string88
.ends
.unbackground 4724 4759
.org 4760
.section "scene1C static strings 89" overwrite
  .db 1
  .dw scene1C_string89
.ends
.unbackground 4763 4768
.org 4769
.section "scene1C static strings 90" overwrite
  .db 1
  .dw scene1C_string90
.ends
.unbackground 4772 4803
.org 4804
.section "scene1C static strings 91" overwrite
  .db 1
  .dw scene1C_string91
.ends
.unbackground 4807 4832
.org 4833
.section "scene1C static strings 92" overwrite
  .db 1
  .dw scene1C_string92
.ends
.unbackground 4836 4861
.org 4862
.section "scene1C static strings 93" overwrite
  .db 1
  .dw scene1C_string93
.ends
.unbackground 4865 4892
.org 4893
.section "scene1C static strings 94" overwrite
  .db 1
  .dw scene1C_string94
.ends
.unbackground 4896 4923
.org 4924
.section "scene1C static strings 95" overwrite
  .db 1
  .dw scene1C_string95
.ends
.unbackground 4927 4946
.org 4947
.section "scene1C static strings 96" overwrite
  .db 1
  .dw scene1C_string96
.ends
.unbackground 4950 4977
.org 4978
.section "scene1C static strings 97" overwrite
  .db 1
  .dw scene1C_string97
.ends
.unbackground 4981 5006
.org 5007
.section "scene1C static strings 98" overwrite
  .db 1
  .dw scene1C_string98
.ends
.unbackground 5010 5035
.org 5036
.section "scene1C static strings 99" overwrite
  .db 1
  .dw scene1C_string99
.ends
.unbackground 5039 5066
.org 5067
.section "scene1C static strings 100" overwrite
  .db 1
  .dw scene1C_string100
.ends
.unbackground 5070 5097
.org 5098
.section "scene1C static strings 101" overwrite
  .db 1
  .dw scene1C_string101
.ends
.unbackground 5101 5110
.org 5112
.section "scene1C static strings 103" overwrite
  .db 1
  .dw scene1C_string103
.ends
.unbackground 5115 5126
.org 5127
.section "scene1C static strings 104" overwrite
  .db 1
  .dw scene1C_string104
.ends
.unbackground 5130 5151
.org 5154
.section "scene1C static strings 107" overwrite
  .db 1
  .dw scene1C_string107
.ends
.unbackground 5157 5168
.org 5170
.section "scene1C static strings 109" overwrite
  .db 1
  .dw scene1C_string109
.ends
.unbackground 5173 5184
.org 5185
.section "scene1C static strings 110" overwrite
  .db 1
  .dw scene1C_string110
.ends
.unbackground 5188 5215
.org 5218
.section "scene1C static strings 113" overwrite
  .db 1
  .dw scene1C_string113
.ends
.unbackground 5221 5232
.org 5233
.section "scene1C static strings 114" overwrite
  .db 1
  .dw scene1C_string114
.ends
.unbackground 5236 5247
.org 5248
.section "scene1C static strings 115" overwrite
  .db 1
  .dw scene1C_string115
.ends
.unbackground 5251 5278
.org 5279
.section "scene1C static strings 116" overwrite
  .db 1
  .dw scene1C_string116
.ends
.unbackground 5282 5309
.org 5311
.section "scene1C static strings 118" overwrite
  .db 1
  .dw scene1C_string118
.ends
.unbackground 5314 5331
.org 5332
.section "scene1C static strings 119" overwrite
  .db 1
  .dw scene1C_string119
.ends
.unbackground 5335 5342
.org 5343
.section "scene1C static strings 120" overwrite
  .db 1
  .dw scene1C_string120
.ends
.unbackground 5346 5357
.org 5359
.section "scene1C static strings 122" overwrite
  .db 1
  .dw scene1C_string122
.ends
.unbackground 5362 5387
.org 5389
.section "scene1C static strings 124" overwrite
  .db 1
  .dw scene1C_string124
.ends
.unbackground 5392 5417
.org 5418
.section "scene1C static strings 125" overwrite
  .db 1
  .dw scene1C_string125
.ends
.unbackground 5421 5448
.org 5450
.section "scene1C static strings 127" overwrite
  .db 1
  .dw scene1C_string127
.ends
.unbackground 5453 5478
.org 5479
.section "scene1C static strings 128" overwrite
  .db 1
  .dw scene1C_string128
.ends
.unbackground 5482 5503
.org 5504
.section "scene1C static strings 129" overwrite
  .db 1
  .dw scene1C_string129
.ends
.unbackground 5507 5528
.org 5529
.section "scene1C static strings 130" overwrite
  .db 1
  .dw scene1C_string130
.ends
.unbackground 5532 5545
.org 5546
.section "scene1C static strings 131" overwrite
  .db 1
  .dw scene1C_string131
.ends
.unbackground 5549 5572
.org 5573
.section "scene1C static strings 132" overwrite
  .db 1
  .dw scene1C_string132
.ends
.unbackground 5576 5597
.org 5598
.section "scene1C static strings 133" overwrite
  .db 1
  .dw scene1C_string133
.ends
.unbackground 5601 5620
.org 5621
.section "scene1C static strings 134" overwrite
  .db 1
  .dw scene1C_string134
.ends
.unbackground 5624 5647
.org 5648
.section "scene1C static strings 135" overwrite
  .db 1
  .dw scene1C_string135
.ends
.unbackground 5651 5672
.org 5673
.section "scene1C static strings 136" overwrite
  .db 1
  .dw scene1C_string136
.ends
.unbackground 5676 5697
.org 5698
.section "scene1C static strings 137" overwrite
  .db 1
  .dw scene1C_string137
.ends
.unbackground 5701 5720
.org 5722
.section "scene1C static strings 139" overwrite
  .db 1
  .dw scene1C_string139
.ends
.unbackground 5725 5752
.org 5753
.section "scene1C static strings 140" overwrite
  .db 1
  .dw scene1C_string140
.ends
.unbackground 5756 5783
.org 5784
.section "scene1C static strings 141" overwrite
  .db 1
  .dw scene1C_string141
.ends
.unbackground 5787 5814
.org 5816
.section "scene1C static strings 143" overwrite
  .db 1
  .dw scene1C_string143
.ends
.unbackground 5819 5850
.org 5851
.section "scene1C static strings 144" overwrite
  .db 1
  .dw scene1C_string144
.ends
.unbackground 5854 5885
.org 5886
.section "scene1C static strings 145" overwrite
  .db 1
  .dw scene1C_string145
.ends
.unbackground 5889 5920
.org 5921
.section "scene1C static strings 146" overwrite
  .db 1
  .dw scene1C_string146
.ends
.unbackground 5924 5955
.org 5957
.section "scene1C static strings 148" overwrite
  .db 1
  .dw scene1C_string148
.ends
.unbackground 5960 5991
.org 5994
.section "scene1C static strings 151" overwrite
  .db 1
  .dw scene1C_string151
.ends
.unbackground 5997 6002
.org 6003
.section "scene1C static strings 152" overwrite
  .db 1
  .dw scene1C_string152
.ends
.unbackground 6006 6027
.org 6030
.section "scene1C static strings 155" overwrite
  .db 1
  .dw scene1C_string155
.ends
.unbackground 6033 6060
