.unbackground $3D47 $7FFF
.define printSimpleString $688F
.define stringSrcPtr $00BE
.bank 0 slot 0
.orga $4288
.section "stdStringLookup fix 0" overwrite
  jsr doNewStandardStringLookup
.ends
.bank 0 slot 0
.orga $4391
.section "stdStringLookup fix 1" overwrite
  jsr doNewStandardStringLookup
.ends
.bank 0 slot 0
.orga $43A8
.section "stdStringLookup fix 2" overwrite
  jsr doNewStandardStringLookup
.ends
.bank 0 slot 0
.orga $43BF
.section "stdStringLookup fix 3" overwrite
  jsr doNewStandardStringLookup
.ends
.bank 0 slot 0
.orga $43D6
.section "stdStringLookup fix 4" overwrite
  jsr doNewStandardStringLookup
.ends
.bank 0 slot 0
.orga $43EE
.section "stdStringLookup fix 5" overwrite
  jsr doNewStandardStringLookup
.ends
.bank 0 slot 0
.orga $4405
.section "stdStringLookup fix 6" overwrite
  jsr doNewStandardStringLookup
.ends
.bank 0 slot 0
.orga $441C
.section "stdStringLookup fix 7" overwrite
  jsr doNewStandardStringLookup
.ends
.bank 0 slot 0
.orga $4433
.section "stdStringLookup fix 8" overwrite
  jsr doNewStandardStringLookup
.ends
.bank 0 slot 0
.orga $444B
.section "stdStringLookup fix 9" overwrite
  jsr doNewStandardStringLookup
.ends
.bank 0 slot 0
.orga $4462
.section "stdStringLookup fix 10" overwrite
  jsr doNewStandardStringLookup
.ends
.bank 0 slot 0
.orga $4479
.section "stdStringLookup fix 11" overwrite
  jsr doNewStandardStringLookup
.ends
.bank 0 slot 0
.orga $4490
.section "stdStringLookup fix 12" overwrite
  jsr doNewStandardStringLookup
.ends
.bank 0 slot 0
.orga $588A
.section "stdStringLookup fix 13" overwrite
  jsr doNewStandardStringLookup
.ends
.bank 0 slot 0
.orga $5927
.section "stdStringLookup fix 14" overwrite
  jsr doNewStandardStringLookup
.ends
.bank 0 slot 0
.orga $5943
.section "stdStringLookup fix 15" overwrite
  jsr doNewStandardStringLookup
.ends
.bank 0 slot 0
.orga $5979
.section "stdStringLookup fix 16" overwrite
  jsr doNewStandardStringLookup
.ends
.bank 0 slot 0
.orga $59C5
.section "stdStringLookup fix 17" overwrite
  jsr doNewStandardStringLookup
.ends
.bank 0 slot 0
.orga $5A62
.section "stdStringLookup fix 18" overwrite
  jsr doNewStandardStringLookup
.ends
.bank 0 slot 0
.orga $5A7E
.section "stdStringLookup fix 19" overwrite
  jsr doNewStandardStringLookup
.ends
