.org 13796
.section "system static strings 0" overwrite
  .db 1
  .dw system_string0
.ends
.unbackground 13799 13816
.org 13817
.section "system static strings 1" overwrite
  .db 1
  .dw system_string1
.ends
.unbackground 13820 13823
.org 13824
.section "system static strings 2" overwrite
  .db 1
  .dw system_string2
.ends
.unbackground 13827 13830
.org 13831
.section "system static strings 3" overwrite
  .db 1
  .dw system_string3
.ends
.unbackground 13834 13853
.org 13854
.section "system static strings 4" overwrite
  .db 1
  .dw system_string4
.ends
.unbackground 13857 13864
.org 13865
.section "system static strings 5" overwrite
  .db 1
  .dw system_string5
.ends
.unbackground 13868 13875
.org 13876
.section "system static strings 6" overwrite
  .db 1
  .dw system_string6
.ends
.unbackground 13879 13886
.org 13887
.section "system static strings 7" overwrite
  .db 1
  .dw system_string7
.ends
.unbackground 13890 13897
.org 13898
.section "system static strings 8" overwrite
  .db 1
  .dw system_string8
.ends
.unbackground 13901 13918
.org 13919
.section "system static strings 9" overwrite
  .db 1
  .dw system_string9
.ends
.unbackground 13922 13943
.org 13944
.section "system static strings 10" overwrite
  .db 1
  .dw system_string10
.ends
.unbackground 13947 13964
.org 13965
.section "system static strings 11" overwrite
  .db 1
  .dw system_string11
.ends
.unbackground 13968 13985
.org 13986
.section "system static strings 12" overwrite
  .db 1
  .dw system_string12
.ends
.unbackground 13989 14014
.org 14015
.section "system static strings 13" overwrite
  .db 1
  .dw system_string13
.ends
.unbackground 14018 14035
.org 14036
.section "system static strings 14" overwrite
  .db 1
  .dw system_string14
.ends
.unbackground 14039 14066
.org 14067
.section "system static strings 15" overwrite
  .db 1
  .dw system_string15
.ends
.unbackground 14070 14093
.org 14094
.section "system static strings 16" overwrite
  .db 1
  .dw system_string16
.ends
.unbackground 14097 14120
.org 14121
.section "system static strings 17" overwrite
  .db 1
  .dw system_string17
.ends
.unbackground 14124 14135
.org 14136
.section "system static strings 18" overwrite
  .db 1
  .dw system_string18
.ends
.unbackground 14139 14144
.org 14145
.section "system static strings 19" overwrite
  .db 1
  .dw system_string19
.ends
.unbackground 14148 14155
.org 14156
.section "system static strings 20" overwrite
  .db 1
  .dw system_string20
.ends
.unbackground 14159 14172
.org 18325
.section "system static strings 21" overwrite
  .db 1
  .dw system_string21
.ends
.unbackground 18328 18347
.org 103
.section "system static strings 22" overwrite
  .db 1
  .dw system_string22
.ends
.unbackground 106 123
.org 124
.section "system static strings 23" overwrite
  .db 1
  .dw system_string23
.ends
.unbackground 127 146
