.org 12300
.section "system static strings 0" overwrite
  .db 1
  .dw system_string0
.ends
.unbackground 12303 12320
.org 12321
.section "system static strings 1" overwrite
  .db 1
  .dw system_string1
.ends
.unbackground 12324 12327
.org 12328
.section "system static strings 2" overwrite
  .db 1
  .dw system_string2
.ends
.unbackground 12331 12334
.org 12335
.section "system static strings 3" overwrite
  .db 1
  .dw system_string3
.ends
.unbackground 12338 12357
.org 12358
.section "system static strings 4" overwrite
  .db 1
  .dw system_string4
.ends
.unbackground 12361 12368
.org 12369
.section "system static strings 5" overwrite
  .db 1
  .dw system_string5
.ends
.unbackground 12372 12379
.org 12380
.section "system static strings 6" overwrite
  .db 1
  .dw system_string6
.ends
.unbackground 12383 12390
.org 12391
.section "system static strings 7" overwrite
  .db 1
  .dw system_string7
.ends
.unbackground 12394 12401
.org 12402
.section "system static strings 8" overwrite
  .db 1
  .dw system_string8
.ends
.unbackground 12405 12422
.org 12423
.section "system static strings 9" overwrite
  .db 1
  .dw system_string9
.ends
.unbackground 12426 12447
.org 12448
.section "system static strings 10" overwrite
  .db 1
  .dw system_string10
.ends
.unbackground 12451 12468
.org 12469
.section "system static strings 11" overwrite
  .db 1
  .dw system_string11
.ends
.unbackground 12472 12489
.org 12490
.section "system static strings 12" overwrite
  .db 1
  .dw system_string12
.ends
.unbackground 12493 12518
.org 12519
.section "system static strings 13" overwrite
  .db 1
  .dw system_string13
.ends
.unbackground 12522 12539
.org 12540
.section "system static strings 14" overwrite
  .db 1
  .dw system_string14
.ends
.unbackground 12543 12570
.org 12571
.section "system static strings 15" overwrite
  .db 1
  .dw system_string15
.ends
.unbackground 12574 12597
.org 12598
.section "system static strings 16" overwrite
  .db 1
  .dw system_string16
.ends
.unbackground 12601 12624
.org 12625
.section "system static strings 17" overwrite
  .db 1
  .dw system_string17
.ends
.unbackground 12628 12639
.org 12640
.section "system static strings 18" overwrite
  .db 1
  .dw system_string18
.ends
.unbackground 12643 12648
.org 12649
.section "system static strings 19" overwrite
  .db 1
  .dw system_string19
.ends
.unbackground 12652 12659
.org 12660
.section "system static strings 20" overwrite
  .db 1
  .dw system_string20
.ends
.unbackground 12663 12676
