.org 12061
.section "system static strings 0" overwrite
  .db 1
  .dw system_string0
.ends
.unbackground 12064 12081
.org 12082
.section "system static strings 1" overwrite
  .db 1
  .dw system_string1
.ends
.unbackground 12085 12088
.org 12089
.section "system static strings 2" overwrite
  .db 1
  .dw system_string2
.ends
.unbackground 12092 12095
.org 12096
.section "system static strings 3" overwrite
  .db 1
  .dw system_string3
.ends
.unbackground 12099 12118
.org 12119
.section "system static strings 4" overwrite
  .db 1
  .dw system_string4
.ends
.unbackground 12122 12129
.org 12130
.section "system static strings 5" overwrite
  .db 1
  .dw system_string5
.ends
.unbackground 12133 12140
.org 12141
.section "system static strings 6" overwrite
  .db 1
  .dw system_string6
.ends
.unbackground 12144 12151
.org 12152
.section "system static strings 7" overwrite
  .db 1
  .dw system_string7
.ends
.unbackground 12155 12162
.org 12163
.section "system static strings 8" overwrite
  .db 1
  .dw system_string8
.ends
.unbackground 12166 12183
.org 12184
.section "system static strings 9" overwrite
  .db 1
  .dw system_string9
.ends
.unbackground 12187 12208
.org 12209
.section "system static strings 10" overwrite
  .db 1
  .dw system_string10
.ends
.unbackground 12212 12229
.org 12230
.section "system static strings 11" overwrite
  .db 1
  .dw system_string11
.ends
.unbackground 12233 12250
.org 12251
.section "system static strings 12" overwrite
  .db 1
  .dw system_string12
.ends
.unbackground 12254 12279
.org 12280
.section "system static strings 13" overwrite
  .db 1
  .dw system_string13
.ends
.unbackground 12283 12300
.org 12301
.section "system static strings 14" overwrite
  .db 1
  .dw system_string14
.ends
.unbackground 12304 12331
.org 12332
.section "system static strings 15" overwrite
  .db 1
  .dw system_string15
.ends
.unbackground 12335 12358
.org 12359
.section "system static strings 16" overwrite
  .db 1
  .dw system_string16
.ends
.unbackground 12362 12385
.org 12386
.section "system static strings 17" overwrite
  .db 1
  .dw system_string17
.ends
.unbackground 12389 12400
.org 12401
.section "system static strings 18" overwrite
  .db 1
  .dw system_string18
.ends
.unbackground 12404 12409
.org 12410
.section "system static strings 19" overwrite
  .db 1
  .dw system_string19
.ends
.unbackground 12413 12420
.org 12421
.section "system static strings 20" overwrite
  .db 1
  .dw system_string20
.ends
.unbackground 12424 12437
.org 428
.section "system static strings 21" overwrite
  .db 1
  .dw system_string21
.ends
.unbackground 431 460
.org 461
.section "system static strings 22" overwrite
  .db 1
  .dw system_string22
.ends
.unbackground 464 471
