.org 11826
.section "system static strings 0" overwrite
  .db 1
  .dw system_string0
.ends
.unbackground 11829 11846
.org 11847
.section "system static strings 1" overwrite
  .db 1
  .dw system_string1
.ends
.unbackground 11850 11853
.org 11854
.section "system static strings 2" overwrite
  .db 1
  .dw system_string2
.ends
.unbackground 11857 11860
.org 11861
.section "system static strings 3" overwrite
  .db 1
  .dw system_string3
.ends
.unbackground 11864 11883
.org 11884
.section "system static strings 4" overwrite
  .db 1
  .dw system_string4
.ends
.unbackground 11887 11894
.org 11895
.section "system static strings 5" overwrite
  .db 1
  .dw system_string5
.ends
.unbackground 11898 11905
.org 11906
.section "system static strings 6" overwrite
  .db 1
  .dw system_string6
.ends
.unbackground 11909 11916
.org 11917
.section "system static strings 7" overwrite
  .db 1
  .dw system_string7
.ends
.unbackground 11920 11927
.org 11928
.section "system static strings 8" overwrite
  .db 1
  .dw system_string8
.ends
.unbackground 11931 11948
.org 11949
.section "system static strings 9" overwrite
  .db 1
  .dw system_string9
.ends
.unbackground 11952 11973
.org 11974
.section "system static strings 10" overwrite
  .db 1
  .dw system_string10
.ends
.unbackground 11977 11994
.org 11995
.section "system static strings 11" overwrite
  .db 1
  .dw system_string11
.ends
.unbackground 11998 12015
.org 12016
.section "system static strings 12" overwrite
  .db 1
  .dw system_string12
.ends
.unbackground 12019 12044
.org 12045
.section "system static strings 13" overwrite
  .db 1
  .dw system_string13
.ends
.unbackground 12048 12065
.org 12066
.section "system static strings 14" overwrite
  .db 1
  .dw system_string14
.ends
.unbackground 12069 12096
.org 12097
.section "system static strings 15" overwrite
  .db 1
  .dw system_string15
.ends
.unbackground 12100 12123
.org 12124
.section "system static strings 16" overwrite
  .db 1
  .dw system_string16
.ends
.unbackground 12127 12150
.org 12151
.section "system static strings 17" overwrite
  .db 1
  .dw system_string17
.ends
.unbackground 12154 12165
.org 12166
.section "system static strings 18" overwrite
  .db 1
  .dw system_string18
.ends
.unbackground 12169 12174
.org 12175
.section "system static strings 19" overwrite
  .db 1
  .dw system_string19
.ends
.unbackground 12178 12185
.org 12186
.section "system static strings 20" overwrite
  .db 1
  .dw system_string20
.ends
.unbackground 12189 12202
